services:
  bot:
    build: .
    user: root
    ports:
      - 8081:80
    volumes:
      - .config.ini:/var/www/html/.config.ini
      - echo-data:/var/lib/echo-bot
    restart: always

volumes:
  echo-data:
